package apicontract

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
)

// Baseline is the committed compatibility contract for one response: the
// schema_version it was recorded against, plus every leaf path/type
// (Flatten's output) that version GUARANTEES to a consumer. It is loaded from
// a docs/api/schemas/*.baseline.json file.
//
// Unlike the published schema (shape.go), a Baseline is never regenerated by
// routine -update: bumping it is the deliberate act of acknowledging (and
// versioning) a breaking change. See docs/api/compatibility.md.
type Baseline struct {
	SchemaVersion int               `json:"schema_version"`
	Paths         map[string]string `json:"paths"`
}

// RenderBaseline JSON-encodes b deterministically for a committed file.
func RenderBaseline(b Baseline) []byte {
	out, err := json.MarshalIndent(b, "", "  ")
	if err != nil {
		panic(fmt.Sprintf("apicontract: marshal baseline: %v", err))
	}
	return append(out, '\n')
}

// LoadBaseline reads and parses a committed baseline file.
func LoadBaseline(path string) (Baseline, error) {
	raw, err := os.ReadFile(path) //nolint:gosec // G304: path is a fixed, code-controlled test fixture location
	if err != nil {
		return Baseline{}, fmt.Errorf("read baseline %s: %w", path, err)
	}
	var b Baseline
	if err := json.Unmarshal(raw, &b); err != nil {
		return Baseline{}, fmt.Errorf("parse baseline %s: %w", path, err)
	}
	return b, nil
}

// CompareBaseline checks baseline against the CURRENT response's schema
// (currentVersion, the SchemaVersion constant compiled into the response
// type; current, Flatten(BuildSchema(responseType))) and returns every
// breaking change found, sorted for a deterministic message. An empty result
// means current is a backward-compatible superset of what baseline promises.
//
// Three kinds of breaking change are detected, purely from the two maps (no
// I/O — this is what makes it independently unit-testable, see
// apicontract_test.go's TestCompareBaseline_* negative tests):
//
//   - A baseline path is missing from current: the field was REMOVED (or, if
//     a differently-named path appeared in its place, effectively RENAMED —
//     the new name is additive and not itself an error, but the old one going
//     missing still is).
//   - A baseline path resolves to a different type signature in current: the
//     field's TYPE CHANGED (e.g. a string became a number, or a required
//     field became nullable in a way that changes its signature).
//   - baseline.SchemaVersion does not match currentVersion: the two files
//     that are supposed to describe the same contract have drifted apart —
//     either the code bumped SchemaVersion without updating the baseline, or
//     vice versa.
//
// A path present in current but absent from baseline is NOT a breaking
// change — additive fields need no baseline update at all, matching the
// additive-vs-breaking policy in docs/api/compatibility.md.
func CompareBaseline(baseline Baseline, currentVersion int, current map[string]string) []string {
	var broken []string
	if baseline.SchemaVersion != currentVersion {
		broken = append(broken, fmt.Sprintf("schema_version mismatch: baseline records %d, code compiles to %d — "+
			"a version bump must update the baseline in the SAME change", baseline.SchemaVersion, currentVersion))
	}
	for p, wantType := range baseline.Paths {
		gotType, ok := current[p]
		switch {
		case !ok:
			broken = append(broken, fmt.Sprintf("%s: REMOVED (baseline promised type %q)", p, wantType))
		case gotType != wantType:
			broken = append(broken, fmt.Sprintf("%s: type changed %q -> %q", p, wantType, gotType))
		}
	}
	sort.Strings(broken)
	return broken
}
