{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tailscale2otel.fullname" . }}
  labels:
    {{- include "tailscale2otel.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secret }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
