#!/usr/bin/env bash
# notices.sh — regenerate the third-party software notices for the SHIPPED binary.
#
# Emits THIRD_PARTY_NOTICES.md: for every Go module in the import graph of
# ./cmd/tailscale2otel, the module name + version + detected license + source URL,
# followed by the verbatim LICENSE text and (where present) the verbatim NOTICE file
# — the latter satisfying Apache-2.0 §4(d). Our own module is excluded.
#
# This is a RELEASE ARTIFACT, not a committed file: it changes on every dependency bump,
# so committing+gating it would break Renovate automerge (hosted Renovate can't self-
# regenerate it). Instead the image build bakes it into /licenses/ and the release
# pipeline attaches it to the GitHub Release. Output is deterministic (sorted, byte-stable)
# for a given module set, so independent regenerations agree.
#
# Env:
#   GO_LICENSES   go-licenses binary (default: go-licenses on PATH)
#   TARGET        package to analyse (default: ./cmd/tailscale2otel)
#   OUT           output file (default: THIRD_PARTY_NOTICES.md)
set -euo pipefail

GO_LICENSES="${GO_LICENSES:-go-licenses}"
TARGET="${TARGET:-./cmd/tailscale2otel}"
OUT="${OUT:-THIRD_PARTY_NOTICES.md}"
SELF="github.com/rknightion/tailscale2otel"
TMPL="$(cd "$(dirname "$0")" && pwd)/notices.tsv.tmpl"

command -v "$GO_LICENSES" >/dev/null 2>&1 || {
  echo "notices: go-licenses not found ('$GO_LICENSES') — install with 'go install github.com/google/go-licenses@v1.6.0'" >&2
  exit 1
}

# go-licenses reads LICENSE/NOTICE files from the module cache; make sure it's populated.
go mod download

# One go-licenses pass -> TSV (name<TAB>version<TAB>license<TAB>url<TAB>licensePath), sorted
# byte-stably by module name. stderr carries only benign "non-Go code"/"empty version" warnings;
# a hard failure still propagates via pipefail (the exit code survives 2>/dev/null).
tsv="$(mktemp)"
trap 'rm -f "$tsv"' EXIT
"$GO_LICENSES" report "$TARGET" --template "$TMPL" --ignore "$SELF" 2>/dev/null \
  | LC_ALL=C sort -t "$(printf '\t')" -k1,1 > "$tsv"

[ -s "$tsv" ] || { echo "notices: go-licenses produced no modules — aborting" >&2; exit 1; }

{
  cat <<'HDR'
# Third-Party Software Notices

<!-- GENERATED by `scripts/notices.sh` (go-licenses). DO NOT EDIT BY HAND. -->
<!-- This file is a build/release artifact regenerated on every dependency change; it is
     baked into the container image at /licenses/ and attached to each GitHub Release. -->

tailscale2otel is licensed under **Apache-2.0** (see LICENSE / LICENSING.md). The compiled
binary incorporates the third-party Go modules listed below. Each module's license text —
and its NOTICE file where one is provided (Apache-2.0 §4(d)) — is reproduced verbatim. These
modules retain their own upstream licenses; the combined binary is distributed under Apache-2.0.
HDR

  while IFS="$(printf '\t')" read -r name version lic url path; do
    [ -n "$name" ] || continue
    printf '\n================================================================================\n'
    printf '%s (%s)\n' "$name" "$version"
    printf 'License: %s\n' "$lic"
    printf 'Source: %s\n' "$url"
    printf -- '--------------------------------------------------------------------------------\n'
    if [ -n "$path" ] && [ -f "$path" ]; then
      cat "$path"
    else
      printf '(no license file detected by go-licenses)\n'
    fi
    # Apache-2.0 §4(d): include the sibling NOTICE file if the module ships one.
    if [ -n "$path" ]; then
      dir="$(dirname "$path")"
      for n in NOTICE NOTICE.txt NOTICE.md notice notice.txt; do
        if [ -f "$dir/$n" ]; then
          printf '\n----- NOTICE (%s) -----\n' "$name"
          cat "$dir/$n"
          break
        fi
      done
    fi
  done < "$tsv"
} > "$OUT.tmp"
mv -f "$OUT.tmp" "$OUT"

echo "notices: wrote $OUT ($(grep -c '^License: ' "$OUT") modules)"
