package config

import (
	"os"
	"path/filepath"
	"runtime"
)

// LegacyCheckpointPath is the checkpoint location this project shipped as the
// only default. It is correct inside the container image (which pre-seeds the
// directory owned by uid 65532) and in the Helm chart (which sets it explicitly
// and mounts a volume there), and both continue to use it.
//
// It is wrong for a NATIVE run: on Linux only root can create /var/lib
// subdirectories, and on macOS and Windows the path does not exist at all —
// yet releases ship binaries for all three. The result was a silent degrade to
// in-memory checkpoints, so every restart cold-started the window collectors
// from initial_lookback and re-fetched (or missed) records (#336).
const LegacyCheckpointPath = "/var/lib/tailscale2otel/checkpoints.json"

// stateDirName namespaces this project's state under whichever per-user state
// directory the platform uses.
const stateDirName = "tailscale2otel"

// DefaultCheckpointPath returns the platform-appropriate checkpoint file path
// for a native run, following each platform's own convention:
//
//	Linux/BSD  $XDG_STATE_HOME/tailscale2otel, else ~/.local/state/tailscale2otel
//	macOS      ~/Library/Application Support/tailscale2otel
//	Windows    %LocalAppData%\tailscale2otel
//
// State — a cursor that may be regenerated by refetching — belongs in the state
// directory rather than the config or cache directory: config is for things the
// operator edits, and a cache may be purged at any time. Go's os.UserConfigDir
// deliberately has no state equivalent, hence the explicit handling here.
//
// If no home directory can be resolved (a daemon with an empty environment,
// say) this returns LegacyCheckpointPath. That is the least-bad answer: it may
// well be writable, and if it is not, checkpointStore's existing unwritable-path
// WARN degrades gracefully. Returning "" would be read as "use the memory
// store" and would silence that warning, which is strictly worse.
func DefaultCheckpointPath() string {
	dir := userStateDir()
	if dir == "" {
		return LegacyCheckpointPath
	}
	return filepath.Join(dir, stateDirName, "checkpoints.json")
}

func userStateDir() string {
	switch runtime.GOOS {
	case "windows":
		// LocalAppData, not AppData: checkpoints are machine-local state and
		// must not follow a roaming profile between machines.
		return os.Getenv("LocalAppData")
	case "darwin":
		home := homeDir()
		if home == "" {
			return ""
		}
		return filepath.Join(home, "Library", "Application Support")
	default:
		if xdg := os.Getenv("XDG_STATE_HOME"); xdg != "" {
			return xdg
		}
		home := homeDir()
		if home == "" {
			return ""
		}
		return filepath.Join(home, ".local", "state")
	}
}

// homeDir resolves the user's home without os.UserHomeDir's error handling,
// and treats an empty value as "unresolvable" so callers get one signal.
func homeDir() string {
	if h := os.Getenv("HOME"); h != "" {
		return h
	}
	if runtime.GOOS == "windows" {
		return os.Getenv("USERPROFILE")
	}
	return ""
}
