package s3

import (
	"net/http"
	"strings"
	"testing"
	"time"
)

// The vectors below were produced by botocore — AWS's own SigV4 implementation,
// the one the official SDK signs with — and pasted here verbatim. That is the
// whole point of them: they are an INDEPENDENT authority on what S3 will
// reconstruct, so a signature this package computes matching one is evidence
// that a real bucket will accept it. A vector generated by this package would
// only prove it had not changed.
//
// Regenerate with (botocore installed):
//
//	python3 -c '
//	import hashlib
//	from botocore.auth import S3SigV4Auth
//	from botocore.awsrequest import AWSRequest
//	from botocore.credentials import Credentials
//	c = Credentials("AKIAIOSFODNN7EXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY")
//	r = AWSRequest(method="GET", url="<url>",
//	               headers={"X-Amz-Content-Sha256": hashlib.sha256(b"").hexdigest()})
//	r.context["client_region"] = "<region>"
//	r.context["payload_signing_enabled"] = False
//	S3SigV4Auth(c, "s3", "<region>").add_auth(r)
//	print(r.headers["X-Amz-Date"], r.headers["Authorization"])'
//
// The signing timestamp is part of each vector because botocore stamps the
// request with its own clock; the test replays that exact instant rather than
// trying to freeze it.
//
// TRAP, learned the hard way: it must be S3SigV4Auth, NOT the generic SigV4Auth.
// The generic signer URI-encodes the canonical path a SECOND time, so a key
// containing "%20" signs as "%2520"; S3 is the service that does not do that.
// Three of the four vectors below are identical either way, because a path with
// no special characters encodes to itself — so a vector set without the last
// case would pass against a double-encoding implementation and fail in
// production the first time a key contained a space.
var sigVectors = []struct {
	name, url, region, akid, secret, token, date, signed, want string
}{
	{
		name:   "virtual-host list",
		url:    "https://examplebucket.s3.eu-west-2.amazonaws.com/?list-type=2&prefix=flow%2F2026%2F07%2F24%2F",
		region: "eu-west-2",
		akid:   "AKIAIOSFODNN7EXAMPLE",
		secret: "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY",
		date:   "20260724T141217Z",
		signed: "host;x-amz-content-sha256;x-amz-date",
		want:   "8be8814fee02fee864127a103624a9cbd62569ee5b8bd6c01c36896804c340cc",
	},
	{
		name:   "path-style get",
		url:    "https://minio.example.com:9000/mybucket/flow/2026/07/24/2026-07-24-09-00-00.ndjson.zst",
		region: "us-east-1",
		akid:   "AKIAIOSFODNN7EXAMPLE",
		secret: "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY",
		date:   "20260724T141217Z",
		signed: "host;x-amz-content-sha256;x-amz-date",
		want:   "2b89d02517c04ef8b8592965f78e7dbd5905b8eeafd2d5048858a1487d7d4bd0",
	},
	{
		name:   "session token",
		url:    "https://examplebucket.s3.eu-west-2.amazonaws.com/?continuation-token=1%2FabC%3D&list-type=2",
		region: "eu-west-2",
		akid:   "ASIAEXAMPLE",
		secret: "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY",
		token:  "SESSIONTOKEN123",
		date:   "20260724T141217Z",
		signed: "host;x-amz-content-sha256;x-amz-date;x-amz-security-token",
		want:   "f9b19833bd3c9bcb0fff94e1d621c95525ee52a2236ee1ab38080239eefc2a90",
	},
	{
		name:   "key with spaces and plus",
		url:    "https://examplebucket.s3.eu-west-2.amazonaws.com/flow/a%20b%2Bc.ndjson",
		region: "eu-west-2",
		akid:   "AKIAIOSFODNN7EXAMPLE",
		secret: "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY",
		date:   "20260724T141217Z",
		signed: "host;x-amz-content-sha256;x-amz-date",
		want:   "dac719631767999c495eb1667639cd8a774c6277f494f8d9a1f0f4659c52aeba",
	},
}

func TestSign_MatchesAWSOwnImplementation(t *testing.T) {
	for _, tc := range sigVectors {
		t.Run(tc.name, func(t *testing.T) {
			at, err := time.Parse("20060102T150405Z", tc.date)
			if err != nil {
				t.Fatalf("vector date: %v", err)
			}
			req, err := http.NewRequest(http.MethodGet, tc.url, nil)
			if err != nil {
				t.Fatalf("request: %v", err)
			}

			signer{region: tc.region}.sign(req, Credentials{
				AccessKeyID: tc.akid, SecretAccessKey: tc.secret, SessionToken: tc.token,
			}, at)

			auth := req.Header.Get("Authorization")
			if got := field(auth, "Signature="); got != tc.want {
				t.Errorf("signature = %s\n           want %s\nauth: %s", got, tc.want, auth)
			}
			if got := field(auth, "SignedHeaders="); got != tc.signed {
				t.Errorf("signed headers = %s, want %s", got, tc.signed)
			}
			if got := req.Header.Get("X-Amz-Content-Sha256"); got != emptyPayloadHash {
				t.Errorf("x-amz-content-sha256 = %q; S3 requires the payload hash as a header too", got)
			}
		})
	}
}

// field reads one comma-terminated value out of an Authorization header.
func field(auth, key string) string {
	i := strings.Index(auth, key)
	if i < 0 {
		return ""
	}
	v := auth[i+len(key):]
	if j := strings.Index(v, ","); j >= 0 {
		v = v[:j]
	}
	return strings.TrimSpace(v)
}

// Credentials that expire early are the normal case on IRSA and instance
// profiles, and a stale signature is a 403 rather than a retry — so the token
// must be signed, not merely sent.
func TestSign_SessionTokenIsSignedNotJustSent(t *testing.T) {
	req, err := http.NewRequest(http.MethodGet, "https://b.s3.eu-west-2.amazonaws.com/?list-type=2", nil)
	if err != nil {
		t.Fatal(err)
	}
	signer{region: "eu-west-2"}.sign(req, Credentials{
		AccessKeyID: "A", SecretAccessKey: "S", SessionToken: "TOK",
	}, time.Unix(0, 0))

	auth := req.Header.Get("Authorization")
	if !strings.Contains(field(auth, "SignedHeaders="), "x-amz-security-token") {
		t.Errorf("SignedHeaders = %q, want the security token covered", field(auth, "SignedHeaders="))
	}
	if req.Header.Get("X-Amz-Security-Token") != "TOK" {
		t.Error("the security token was not sent")
	}
}

// Static credentials carry no token, and signing an empty one changes the
// canonical request into something the server will not reconstruct.
func TestSign_NoTokenHeaderWithStaticCredentials(t *testing.T) {
	req, err := http.NewRequest(http.MethodGet, "https://b.s3.eu-west-2.amazonaws.com/?list-type=2", nil)
	if err != nil {
		t.Fatal(err)
	}
	signer{region: "eu-west-2"}.sign(req, Credentials{AccessKeyID: "A", SecretAccessKey: "S"}, time.Unix(0, 0))

	if _, ok := req.Header["X-Amz-Security-Token"]; ok {
		t.Error("an empty security token was sent")
	}
	if strings.Contains(field(req.Header.Get("Authorization"), "SignedHeaders="), "security-token") {
		t.Error("an absent security token was signed")
	}
}
