name: actionlint
on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']
permissions: {}
concurrency:
  group: actionlint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    permissions:
      contents: read
    uses: rknightion/.github/.github/workflows/actionlint.yml@873962525bd50b84dfdb3226efab8c8e2cd6a9a2 # v1.11.0
