name: Dependency review
on:
  pull_request:
    branches: [main]
permissions: {}
jobs:
  dependency-review:
    permissions:
      contents: read
      pull-requests: write
    uses: rknightion/.github/.github/workflows/dependency-review.yml@8629ccbdd3dc4eed776ca42e1896ab37f94d88d6 # main
