name: Dependency review
on:
  pull_request:
    branches: [main]
permissions: {}
concurrency:
  group: dependency-review-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dependency-review:
    permissions:
      contents: read
      pull-requests: write
    uses: rknightion/.github/.github/workflows/dependency-review.yml@32b5e93dcbb5419fd955f9eb913720cfbc1c13f8 # v1.25.0
