name: Dependency review
on:
  pull_request:
    branches: [main]
permissions: {}
concurrency:
  group: dependency-review-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dependency-review:
    permissions:
      contents: read
      pull-requests: write
    uses: rknightion/.github/.github/workflows/dependency-review.yml@873962525bd50b84dfdb3226efab8c8e2cd6a9a2 # v1.11.0
