name: Docker Security
on:
  push:
    branches: [main]
  schedule:
    - cron: '33 5 * * 2'
  workflow_dispatch:
permissions: {}
concurrency:
  group: docker-security-${{ github.ref }}
  cancel-in-progress: false

jobs:
  docker-security:
    permissions:
      contents: read
      security-events: write
    uses: rknightion/.github/.github/workflows/docker-security.yml@79a72d215e806c12876526ff30fbd524250e1bf9 # v1.17.1
