name: Docker Security
on:
  push:
    branches: [main]
  schedule:
    - cron: '33 5 * * 2'
  workflow_dispatch:
permissions: {}
jobs:
  docker-security:
    permissions:
      contents: read
      security-events: write
    uses: rknightion/.github/.github/workflows/docker-security.yml@8629ccbdd3dc4eed776ca42e1896ab37f94d88d6 # main
