name: Docker Security
on:
  push:
    branches: [main]
  schedule:
    - cron: '33 5 * * 2'
  workflow_dispatch:
permissions: {}
concurrency:
  group: docker-security-${{ github.ref }}
  cancel-in-progress: false

jobs:
  docker-security:
    permissions:
      contents: read
      security-events: write
    uses: rknightion/.github/.github/workflows/docker-security.yml@e17f6f1a010f50cf878b310cf90820f14c0bbbf6 # v1.25.2
