name: Scorecard
on:
  push:
    branches: [main]
  schedule:
    - cron: '41 7 * * 3'
permissions: {}
concurrency:
  group: scorecard-${{ github.ref }}
  cancel-in-progress: false

jobs:
  scorecard:
    permissions:
      security-events: write
      id-token: write
    uses: rknightion/.github/.github/workflows/scorecard.yml@79a72d215e806c12876526ff30fbd524250e1bf9 # v1.17.1
