name: Scorecard
on:
  push:
    branches: [main]
  schedule:
    - cron: '41 7 * * 3'
permissions: {}
concurrency:
  group: scorecard-${{ github.ref }}
  cancel-in-progress: false

jobs:
  scorecard:
    permissions:
      security-events: write
      id-token: write
    uses: rknightion/.github/.github/workflows/scorecard.yml@9c3981da69a2aa4eecd99e5740335219fd8c6a00 # v1.9.10
